//
// Created by Max Rupplin on 5/11/2026.
//

#ifndef UBUNTU_44D_ORANGE_DEMOCRATUS_MEARVKBUNTU_H
#define UBUNTU_44D_ORANGE_DEMOCRATUS_MEARVKBUNTU_H


class MEARVKBUNTU
{
};


#endif //UBUNTU_44D_ORANGE_DEMOCRATUS_MEARVKBUNTU_H
